name: docker

on:
  push:
  schedule:
  - cron: "22 3 25 * *"
    
jobs:
  docker:
    runs-on: ubuntu-latest
    name: ${{ matrix.tag }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - { directory: bionic,  tag: '18.04' }
          - { directory: focal,   tag: '20.04' }
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    #- name: Set up QEMU
    #  uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.config.directory }}
        tags: rocker/r-ubuntu:${{ matrix.config.tag }}
